### ISSUE TITLE
Selecting Power plants

### ISSUE THREAD

**Issue by cksharma11** [STEP-tw/powergrid-sparks#50]
**As a Player**
I want to select a power plant before buying it
**So that:**

- I can change my selection when I have a change of mind

**Additional Details**

**Acceptance Criteria:**

- [ ]  Criteria 1

- Given Players are on auction phase
- When it's their turn and they click on any power plant
- Then it should be selected and cost of power plant should be displayed

**Comment by deepikabartwal** [comment]
right now didn't handle turns. So moving back to div
